### ISSUE TITLE
Pacman repo is outdated

### ISSUE THREAD

**Issue by julian-poidevin** [nihaals/visual-studio-code-insiders-arch#2]
VSCode Insiders is suggesting me to update for a few days now, without having a new version available from this repository.

When going to the [download page](https://code.visualstudio.com/insiders/) of vscode and trying to download the latest version, the version number is `1.79.0-1684546628`, the latest package version available from your repo is `visual-studio-code-insiders 1.79.0_insider+1684302546-1`.

Is the CI broken ? Maybe Microsoft did some changes on their end and the CI does not work anymore ?

Thanks !

**Comment by nihaals** [comment]
Thanks for the report, I should be able to take a look tomorrow

**Comment by nihaals** [comment]
[This](https://github.com/nihaals/visual-studio-code-insiders-arch/actions/runs/5068071769/jobs/9099990001#step:8:87) seems to be the issue and weirdly it doesn't seem to be a one off like it has been in the past. The file size also should be fitting in GitHub's limits so I'm not sure what might be causing this.

Edit: Looks like this has already been [reported to GitHub](https://github.com/orgs/community/discussions/55820) as a recent breaking change/bug. A temporary solution might be avoiding using the Pacman repo and instead building the package yourself in a similar way to the AUR (as this part is unaffected).

**Comment by julian-poidevin** [comment]
In the [discussion](https://github.com/orgs/community/discussions/55820) you provided, someone came up with [a fix](https://github.com/orgs/community/discussions/55820#discussioncomment-5954778) that consists in :

- running `git config --global http.version HTTP/1.1;` as a `pre_build_commands` and install `git-lfs`.

Would you consider using this fix or you prefer to wait for an official fix from GitHub ?

**Comment by nihaals** [comment]
I'd much rather wait for an actual fix instead of adding a workaround, but depending on how long the issue lasts, I think adding the workaround instead makes sense, especially when it likely doesn't cause much harm. The [action currently used](https://github.com/peaceiris/actions-gh-pages) doesn't have a `pre_build_commands` equivalent input, but as it's a Node action, hopefully just running the Git config command will work. If there isn't an official acknowledgement of the issue by 2023-05-28, I'll try to find a workaround.

**Comment by julian-poidevin** [comment]
Understood. I hope GitHub will have a look at it : the discussion has been marked "<kbd>Resolved</kbd>" by its original author so I wonder if GitHub will consider reading it.

**Comment by nihaals** [comment]
> I hope GitHub will have a look at it : the discussion has been marked "<kbd>Resolved</kbd>" by its original author so I wonder if GitHub will consider reading it.

This exact point came up [in the replies](https://github.com/community/community/discussions/55820#discussioncomment-5988694) but it sounds like some people made support tickets too which should help.

**Comment by julian-poidevin** [comment]
Some users are reporting the issue is fixed on their side : [here](https://github.com/orgs/community/discussions/55820#discussioncomment-6022073)  and [here](https://github.com/orgs/community/discussions/55820#discussioncomment-6022063).

**Comment by nihaals** [comment]
This issue is now fixed and should update as normal!

**Comment by julian-poidevin** [comment]
Thanks @nihaals, I think you can also unpin the issue.

**Comment by julian-poidevin** [comment]
@nihaals I think we need to re-open the issue, the pipeline failed again : https://github.com/nihaals/visual-studio-code-insiders-arch/actions/runs/5109443290/jobs/9184315423#step:8:88

**Comment by nihaals** [comment]
As this is more of a typical random error I think it makes more sense to keep this as #3. And thanks for reminding me about the pin!
